# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
        # Commented out the check-yaml hook because it seems that it doesn't parse the Helm templates successfully.
        #      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: pretty-format-json
      - id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        additional_dependencies: ["types-PyYAML"]
-   repo: https://github.com/PyCQA/bandit
    rev: "1.7.0"
    hooks:
      - id: bandit
        exclude: "^tests/.*"
-   repo: https://github.com/PyCQA/pydocstyle
    rev: "6.1.1"
    hooks:
      - id: pydocstyle
        exclude: "^tests/.*"
        additional_dependencies: ["toml"]
-   repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: ["python"]
-   repo: local
    hooks:
      - id: pycodestyle
        name: pycodsetyle
        entry: pycodestyle
        language: system
        types: ["python"]
-   repo: https://github.com/jendrikseipp/vulture
    rev: v2.3
    hooks:
      - id: vulture
        args: ["src", "tests"]
